# Generated by Django 3.2.3 on 2021-11-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_genres'),
        ('accounts', '0002_user_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_actors',
            field=models.ManyToManyField(related_name='like_users', to='movies.Actor'),
        ),
    ]
