# Generated by Django 3.2.3 on 2021-11-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('profile_path', models.TextField()),
                ('adventure', models.IntegerField(default=0, null=True)),
                ('fantasy', models.IntegerField(default=0, null=True)),
                ('animation', models.IntegerField(default=0, null=True)),
                ('drama', models.IntegerField(default=0, null=True)),
                ('horror', models.IntegerField(default=0, null=True)),
                ('action', models.IntegerField(default=0, null=True)),
                ('comedy', models.IntegerField(default=0, null=True)),
                ('historic', models.IntegerField(default=0, null=True)),
                ('western', models.IntegerField(default=0, null=True)),
                ('thriller', models.IntegerField(default=0, null=True)),
                ('criminal', models.IntegerField(default=0, null=True)),
                ('documentary', models.IntegerField(default=0, null=True)),
                ('sf', models.IntegerField(default=0, null=True)),
                ('mystery', models.IntegerField(default=0, null=True)),
                ('music', models.IntegerField(default=0, null=True)),
                ('romance', models.IntegerField(default=0, null=True)),
                ('family', models.IntegerField(default=0, null=True)),
                ('millitary', models.IntegerField(default=0, null=True)),
                ('tv', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
